theme: minima
title: notes on Green's functions and Eigenvalue Method
author: Junot LIANG
description: This is a personal notes of learning such a new method to solve problems about wave propagation in composites. 
